// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh manifest`.

import * as $0 from "./routes/api/listen.ts";
import * as $1 from "./routes/api/send.ts";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/Chat.tsx";
import * as $$1 from "./islands/ChatHistory.tsx";
import * as $$2 from "./islands/SendField.tsx";

const manifest = {
  routes: {
    "./routes/api/listen.ts": $0,
    "./routes/api/send.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/Chat.tsx": $$0,
    "./islands/ChatHistory.tsx": $$1,
    "./islands/SendField.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
